### ISSUE TITLE
How do I mute the new Shell Game sound added in 8.3?

### ISSUE THREAD

**Issue by cogar328** [funkydude/MuteSoundFile#12]
Anyone know how to mute this sound that was recently added?  I have looked and looked but can't find it

**Comment by funkydude** [comment]
I know which sound you mean, the sound that plays when you fail. No idea what sound it is though, maybe someone else does.

**Comment by funkydude** [comment]
Unfortunately it's best you take these issues to community forums and community Discord channels

**Comment by cogar328** [comment]
thanks so much for the addon and the response.
Take care
