### ISSUE TITLE
Thanks for this addon!

### ISSUE THREAD

**Issue by nicohagen** [funkydude/MuteSoundFile#15]
Sorry for abusing the issues but just wanted to let ya know i really appreciate your work here. literally could not play my Mag'har Orc warrior without muting the ~10 most annoying sounds. I really hope you make this addon v9.x compatible when its out.

**Comment by funkydude** [comment]
I appreciate the kind words.

If anyone wishes to, they can support my continued addon work by clicking the sponsor button at the top of this page.
