### ISSUE TITLE
Muting sound file causes sound to play for eternity

### ISSUE THREAD

**Issue by Akhorishaan** [funkydude/MuteSoundFile#16]
Muting the sound file ID 2026450 (sound/spells/fx_80_azeritekit_loop_med_01.ogg) causes the sound ID to play forever after using Focused Azerite Beam (Until changing sound channels in the settings or relogging), removing the mute for that sound file ID resolves the issue. Have a video of the issue happening here: https://www.youtube.com/watch?v=mJ146bgtM9Y

Speculation:  Perhaps it is due to the sound being of variable length (For different amounts of haste, the sound is supposed to play until the ability is finished channeling and then stop immediately), likely called by a different bit of sound playing code in WoW that isn't caught by MSF, but for some reason setting the ID to be muted causes WoW to not stop playing the sound.

Edit: Forgot the video

**Comment by funkydude** [comment]
@Akhorishaan Is this still in issue after the shadowlands patch?

**Comment by funkydude** [comment]
It's possible it was related to there being multiple sounds playing for that ability, and it would have required muting all of them. But since there was no response, and since the content is irrelevant now with Shadowlands released, I'll just close this.
