### ISSUE TITLE
Need help locating sound file

### ISSUE THREAD

**Issue by paradisewoods** [funkydude/MuteSoundFile#17]
How can I mute the Dreadwake mount-up noise?
I've tried searching Dreadwake, ship, bells, horn, fog, zeppelin, dock, anything I can think of that's related and I've come up with nothing. I tried both WoWhead and wow.tools/sounds

Any ideas?

**Comment by funkydude** [comment]
Unfortunately it's best you take these issues to community forums and community Discord channels
