### ISSUE TITLE
Help save my DM experience

### ISSUE THREAD

**Issue by Githubgumba** [funkydude/MuteSoundFile#18]
Hi Mr Funk. 
I tried to mute DM's Felrush shout, after reading this line from another user:

"Also the Demon Hunter shouts when you use Felrush :33333"

But I can't get it to work. When I write 33333 in the sound ID (number) field, I get this message 

"There is no sound with id '33333' or you have sound disabled." And my sound is working. 

Anyone knows what I'm doing wrong? Right now, I turn the volume way down, when I play my BE DM 

because of all these fu... HEYAAA sounds..

**Comment by funkydude** [comment]
This addon uses file id's not soundkit id's, so 33333 is wrong.
I did a search on wow.tools and here and the results, maybe blocking these id's will help:
![image](https://user-images.githubusercontent.com/16833/98318365-600f2600-1fd6-11eb-80ed-ddaa3aa7e49b.png)

**Comment by Githubgumba** [comment]
Thx for your reply. :)

They weren't the annoying HEYAAA sounds, I was looking for.
But now I know were to look, and what file types are correct.

Great that you made this mod.
