### ISSUE TITLE
Hello, I have a question 

### ISSUE THREAD

**Issue by Sindail** [funkydude/MuteSoundFile#25]
Hello,

I know this probably is not the place for this, but I saw no other options for contact.

I am intrigued by your addon, but I am stuck. I have been able to lookup sound files on wowhead, but the sound ID (the numbers in parenthesis at the end of the javascript) do not seem to link to a file I can preview in the add sounds. What I am trying to do is mute all the sounds in the fishing area in zereth mortis while fishing up the bait for Hirukon.
If those were included in an optional preset list someplace that would rock. TBH  I don't know exactly how to find the correct files that are playing in that area. Any help would be appreciated.

Thanks

**Comment by funkydude** [comment]
You cannot use wowhead. See here for more info: https://github.com/funkydude/MuteSoundFile/issues/26
