### ISSUE TITLE
Muting sounds does not work

### ISSUE THREAD

**Issue by Gorethrone** [funkydude/MuteSoundFile#26]
Hi,
tried your addon because it would really help me out with my tinnitus. Sadly it does not work, each sound I enter gets not muted and is still hearable ingame. I also tested some other sounds and often I get the message, that the id is not correct, for example 3257.

I wanted to mute my pet idle loop sound, which should be the id 154796 (on top of that I muted any other loop sound which was similar to that 155000, 183864, 119369, 139734, 129286, but none worked)

The sound preview is also not working. If I input an existing id (where no incorrect id message appears) and I press the play preview button, no sounds get played at all.

**Comment by Gorethrone** [comment]
So I tried a little more and playing sounds does work indeed, just not for my sounds... but the ids are the correct ones from wowhead.

**Comment by Gorethrone** [comment]
Ok, the ids on wowhead arent correct in a lot of cases! I found the one I needed with **https://wow.tools/files/sounds.php#search=&page=1**. The sound I needed was called **MON_Mount_Ravager_WingFlaps_Loop** before and now is called **MON_Mount_Ravager_InFlight**...

**Comment by AlexFolland** [comment]
Are you on the right version of Wowhead?  "classic" for vanilla classic, "tbc classic" for tbc classic, and "live" for mainline

**Comment by Gorethrone** [comment]
> Are you on the right version of Wowhead? "classic" for vanilla classic, "tbc classic" for tbc classic, and "live" for mainline

Yes I am :)

**Comment by funkydude** [comment]
This addon requires entry of individual file IDs. Wowhead doesn't provide file IDs it provides "soundkit" IDs which are essentially "groups" of sounds. In other words, you cannot use wowhead. This is why you are guided towards wow.tools in the options.
