### ISSUE TITLE
trying to mute G'eras and the mailboxes in Shat, same noise just different area

### ISSUE THREAD

**Issue by thormourn** [funkydude/MuteSoundFile#28]
so i went to wowhead, found the sound file for g'eras which is im assuming the same sound file as the mailboxes in shattrath, found it was named NaaruLoopGood. loaded up wow.tools/sound, searched naaru, found  601649 | sound/creature/naaru/naruuloopgood.ogg, typed that sound file, 601649 into mutesoundfile, and g'eras and the mailboxes still make noise.

**Comment by funkydude** [comment]
If a sound isn't muted then you don't have the right ID or there are multiple IDs, I suggest you ask wow/addon discords or forums for assistance.
