### ISSUE TITLE
Suggestion:  Sample ["soundList"] dict(s)

### ISSUE THREAD

**Issue by Amadeus-** [funkydude/MuteSoundFile#3]
I was thinking that it might be nice to have a directory here with each file having some of the more common sounds that folks mute.   That way, users could contribute so that all of us aren't having to do all the work.   (In other words, it'd be nice to have some assistance in re-creating all of the muted sounds used in the addon "Mute Annoying WoW Sounds".   There are a LOT of sounds in that addon!)

Obviously, it would require folks feeling comfortable making edits to their WTF settings file -- but, for advanced users, it could save a LOT of time.   It might also provide resources for you to add functionality to this addon for "bulk" adding common sounds based on category, etc.  (Or, provide drop down boxes, etc.)

My thinking/suggestion was to have one directory, and then each file being a different "category" of sounds, etc.  But, there might be a better solution (I'm more of a c/c++ coder than an addon developer!)    Each file could just have something like:
```
			["soundList"] = {
				["fizzlefrosta.ogg"] = 569775,
				["fizzleshadowa.ogg"] = 569776,
				["fizzleholya.ogg"] = 569772,
				["fizzlefirea.ogg"] = 569773,
				["fizzlenaturea.ogg"] = 569774,
			},
```
Then, we could just copy/paste it into our settings file!   Easy-peasy.

Thanks!

**Comment by svetlocrno** [comment]
Grand Expedition Yak vendors:

["vo_grummle_standard_vendor_01"] = 640336,
["vo_grummle_standard_vendor_02"] = 640338,
["vo_grummle_standard_vendor_03"] = 640340,
["vo_grummle_standard_farewell_01"] = 640314,
["vo_grummle_standard_farewell_02"] = 640316,
["vo_grummle_standard_farewell_03"] = 640318,
["vo_grummle_standard_farewell_04"] = 640320,
["vo_grummle_kooky_vendor_01"] = 640180,
["vo_grummle_kooky_vendor_02"] = 640182,
["vo_grummle_kooky_vendor_03"] = 640184,
["vo_grummle_kooky_farewell_01"] = 640158,
["vo_grummle_kooky_farewell_02"] = 640160,
["vo_grummle_kooky_farewell_03"] = 640162,
["vo_grummle_kooky_farewell_04"] = 640164,

**Comment by Amadeus-** [comment]
I also started a thread on the official forums:  [LINK](https://us.forums.blizzard.com/en/wow/t/mutesoundfile-post-sound-ids-here/215444)

**Comment by funkydude** [comment]
Will be working on this next.
