### ISSUE TITLE
Fails to recognize a sound.

### ISSUE THREAD

**Issue by cgsub** [funkydude/MuteSoundFile#35]
## Describe the problem
Doesn't recognize a sound that I can play with /script PlaySound(222482)
From: https://www.wowhead.com/sound=222482/vo-101-fyrakk-235928

### What steps will reproduce the problem?
+
1. Try to add or play the sound in the addon
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
Curseforge v10.2.3 retail dated 2/10/2024

### Do you have an error log of what happened?
MuteSoundFile: There is no sound with id '222482' or you have sound disabled.

### Any additional information? (example: WoW language if not English)
Maybe I don't use it properly, I just added a few sounds before with the addon, so it could just be my mistake?

**Comment by funkydude** [comment]
`PlaySound(222482)` is a **soundkit** NOT a **sound file**.

These are two completely separate forms of ID.
A soundkit can be a collection of multiple sound files.
This addon is designed to mute specific and individual sound files.
