### ISSUE TITLE
Sounds currently not muted (due to patch)

### ISSUE THREAD

**Issue by Zasz333** [funkydude/MuteSoundFile#39]
With the newest patch and the newest version of the addon sounds are not muted. For example I muted the sounds of the grand expedition yak grummles and the addon confirms this but they arent muted. No errors given.

**Comment by funkydude** [comment]
Nothing changed with the patch. Disable all your addons except MuteSoundFile, it will probably start working again.
Now gradually enable a few addons at a time until it breaks again.
When you find out the addon causing it, please let me know so I can investigate.

**Comment by shneedles** [comment]
yesterday I had the same problem. I just wanted to test the addons like you suggested. But I noticed when I logged in for the first time that the problem no longer exists. Before I start wow, I always update my addons with wowup. The only addons updated today were: WeakAuras, Details! and Raider.IO.
Maybe this helps

**Comment by shneedles** [comment]
today I had the problem again. For me it was also due to the addon “leatrix plus”. I have now used an older version of Leatrix Plus. the tortollans on ah-mount are damn annoying

**Comment by Zasz333** [comment]
I got in contact with the author of LTP. The current alpha fixes the mount issue. If you are using the curse client, set it to alpha for that addon and ingame disable the "mute mount sounds" setting. That should fix it.

**Comment by funkydude** [comment]
@Zasz333 Did they explain what they were doing that was causing it?
