### ISSUE TITLE
A Classic version?

### ISSUE THREAD

**Issue by Wisdawn** [funkydude/MuteSoundFile#8]
I don't know how hard this would be, but it doesn't seem like Classic WoW has a radically different directory structure from Retail, so hoping that making MuteSoundFile compatible with Classic is possible.

Muting fizzle and wand sounds is sorely needed in it.

Thank you for working on this addon nevertheless.

**Comment by funkydude** [comment]
Not possible unless Blizz backport the functionality from retail. But the old "replacing sounds" way works.

**Comment by Gogo1951** [comment]
Confirmed! (= You download this (https://www.curseforge.com/wow/addons/mute-wow-sounds) and drop it in your WoW Classic director under "C:\Program Files (x86)\World of Warcraft\_classic_\Sound" -- if your "Ambience" folder is at "C:\Program Files (x86)\World of Warcraft\_classic_\Sound\Ambience" then you've done it right -- and it removes all the annoying sounds like "woosh" when you mash an ability but it's not ready, or stupid hunter bird dive sounds.
